Repository gradle/community, pull requests merged in 2024-06, with the labels that each got.

#33 Disable Key projects until we reach consensus
  mkdocs.yml
Labels: documentation

#39 Remove the gradle.org/community remnants, add gradle.org Analytics
  .github/workflows/deploy.yml
  docs/CONTRIBUTING.md
  mkdocs-dotorg.yml
  mkdocs.yml
Labels: chore

#40 Extend the credits section on the landing
  README.md
Labels: documentation

#41 Add Release Drafter to generate content changelogs and attributions
  .github/release-drafter.yml
  .github/workflows/changelog.yml
Labels: documentation, chore

#44 Update the Gradle Cookbook summary
  docs/cookbook/README.md
Labels: cookbook

#46 Add Gradle Cookbook PDF generator
  .devcontainer/Dockerfile
  .devcontainer/requirements.txt
  .github/workflows/release.yml
  .gitignore
  docs/CONTRIBUTING.md
  docs/cookbook/README.md
  mkdocs.yml
Labels: enhancement, cookbook

#51 Gradle Built Tool -> Gradle Build Tool
  docs/cookbook/README.md
Labels: bug
