Repository gradle/community, pull requests merged in 2024-10, with the labels that each got.

#92 Update gradle.css : darken headers & links in light mode
  docs/assets/css/gradle.css
Labels: enhancement

#91 Cleanup the repo README.md
  README.md
Labels: bug

#94 Add Issue query to the GradleUp projects
  docs/events/hacktoberfest/2024/README.md
Labels: documentation

#95 Add OpenSavvy's ViteJS to the list of Hacktoberfest projects
  docs/events/hacktoberfest/2024/README.md
Labels: hacktoberfest

#97 Resources: Fix the link to professional services, add Slack news
  docs/resources/README.md
Labels: bug

#99 Improve social media metadata for the "Contributing to Documentation" pages
  docs/contributing/documentation/README.md
Labels: documentation, enhancement

#104 Update community-slack.md
  docs/contributing/community-slack.md
Labels: hacktoberfest-accepted

#105 Fix - SEO metadata for GSoC pages.
  docs/contributing/documentation/README.md
  docs/cookbook/CONTRIBUTING.md
  docs/events/gsoc/2023/README.md
  docs/events/gsoc/2024/README.md
  docs/events/gsoc/2024/checkstyle-plugin.md
  docs/events/gsoc/2024/gradle-build-server-android.md
  docs/events/gsoc/2024/gradle-build-server-devx.md
  docs/events/gsoc/README.md
Labels: enhancement

#114 Add #docs to the featured Slack channel
  docs/contributing/community-slack.md
Labels: documentation

#116 Add quick links to the contributor guide + Plugin contributor stub
  .devcontainer/devcontainer.json
  .devcontainer/requirements.txt
  docs/contributing/README.md
  docs/contributing/plugins.md
  mkdocs.yml
Labels: documentation

#117 Embed the contributing slides in the documentation page
  docs/assets/css/gradle.css
  docs/contributing/documentation/Contributing to Gradle Docs.pdf
  docs/contributing/documentation/README.md
Labels: documentation

#111 reviewed list of gradle books - proposal for books.md
  docs/assets/css/gradle.css
  docs/images/covers/cover_image_unavailable.png
  docs/resources/books.md
  mkdocs.yml
  overrides/books.html
Labels: documentation, hacktoberfest-accepted
