Repository gradle/community, pull requests merged in 2024-08, with the labels that each got.

#54 Update the GSoC project statuses and add mid-term demo
  docs/assets/css/gradle.css
  docs/events/gsoc/2024/README.md
  docs/events/gsoc/2024/checkstyle-plugin.md
  docs/events/gsoc/2024/gradle-build-server-android.md
  docs/events/gsoc/2024/gradle-build-server-devx.md
  docs/events/gsoc/README.md
Labels: gsoc

#57 Add the resources page
  docs/assets/css/gradle.css
  docs/images/icons/arrow.svg
  docs/images/icons/book-star.svg
  docs/images/icons/book-tutorial.svg
  docs/images/icons/book-user.svg
  docs/images/icons/bookmark.svg
  docs/images/icons/books.svg
  docs/images/icons/browser.svg
  docs/images/icons/cal.svg
  docs/images/icons/check.svg
  docs/images/icons/clock.svg
  docs/images/icons/close.svg
  docs/images/icons/conference.svg
  docs/images/icons/contributing.svg
  docs/images/icons/discuss.svg
  docs/images/icons/documentation.svg
  docs/images/icons/down-caret.svg
  docs/images/icons/email.svg
  docs/images/icons/external-link.svg
  docs/images/icons/globe.svg
  docs/images/icons/ide.svg
  docs/images/icons/installation.svg
  docs/images/icons/issues.svg
  docs/images/icons/jobs.svg
  docs/images/icons/label.svg
  docs/images/icons/location.svg
  docs/images/icons/meetups.svg
  docs/images/icons/news.svg
  docs/images/icons/phone.svg
  docs/images/icons/play.svg
  docs/images/icons/plugins.svg
  docs/images/icons/quote.svg
  docs/images/icons/sources.svg
  docs/images/icons/ticket.svg
  docs/images/icons/training.svg
  docs/images/icons/video-camera.svg
  docs/images/icons/videos.svg
  docs/resources/README.md
  mkdocs.yml
  overrides/main.html
  overrides/resources.html
Labels: enhancement

#59 Add initial 2024 Survey Landing
  docs/assets/css/gradle.css
  docs/surveys/developer-survey/README.md
  docs/surveys/developer-survey/images/hero.png
  docs/surveys/developer-survey/images/opengraph.png
  mkdocs.yml
Labels: documentation

#60 Use the brand dark color in background images
  mkdocs.yml
Labels: enhancement

#63 Embed the Developer survey
  docs/surveys/developer-survey/README.md
Labels: enhancement

#64 Fix typos and grammar in docs
  docs/README.md
  docs/contributing/README.md
  docs/contributing/spread-the-word.md
  docs/cookbook/android/README.md
  docs/cookbook/kotlin/README.md
Labels: bug

#69 Add support for rendering emoji, checkboxes and tasklists in GitHub style
  mkdocs.yml
Labels: enhancement

#70 Fix image paths in
  docs/events/gsoc/2024/gradle-build-server-android.md
Labels: bug

#71 Add Learning resources to /resources + Enable Google Tag analytics for DPE University links
  docs/assets/css/gradle.css
  docs/assets/js/google-tag-support.js
  docs/images/icons/learn.svg
  docs/resources/README.md
  mkdocs.yml
  overrides/resources.html
Labels: enhancement, chore

#72 Use Google Tag Manager injection instead of GA4
  mkdocs.yml
  overrides/main.html
  overrides/partials/integrations/analytics/custom.html
Labels: chore

#73 Add the Developer survey announcement
  docs/assets/css/gradle.css
  overrides/main.html
Labels: enhancement
